### ISSUE TITLE
Yaml within YAML issue

### ISSUE THREAD

**Issue by jamielsharief** [originphp/yaml#1]
When using multi-line literals `|` it still parses data if there is YAML in this, which is incorrect.

```yml
config:
  user.user-data: |
    #cloud data
    ssh_pwauth: yes
    
    users:
      - name: ubuntu
        passwd: "$6$3N1u1YuLwzEGohID$O4qofI3MNgqr4tmO7SxrSWpE79jZ0Q6c0CfmI/yGi21Nfq.rF/RTSzvEqb.dV/f8QepZHwaNgfOcOCcj9T0Va1"
        lock_passwd: false
        groups: lxd
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
description: LXD profile for virtual machines
devices:
 config:
   source: cloud-init:config
   type: disk
name: vm
```
